"""Repository layer for SQLite application metadata (caller-owned transactions)."""

from __future__ import annotations

from app.repositories.agent_runs import (
    AgentRunDuplicateError,
    AgentRunNotFoundError,
    AgentRunRepository,
    AgentRunRepositoryError,
    AgentRunStateError,
    AgentRunValidationError,
    langgraph_thread_id,
    sanitize_run_error,
)
from app.repositories.conversations import (
    ConversationDuplicateError,
    ConversationMessageError,
    ConversationNotFoundError,
    ConversationPayloadError,
    ConversationRepository,
    ConversationRepositoryError,
    validate_structured_payload,
)
from app.repositories.preferences import (
    PreferencesNotFoundError,
    PreferencesRepository,
    PreferencesRepositoryError,
    PreferencesValidationError,
)
from app.repositories.profile_drafts import (
    ProfileDraftNotFoundError,
    ProfileDraftRecord,
    ProfileDraftRepository,
    ProfileDraftRepositoryError,
    ProfileDraftStateError,
    ProfileDraftValidationError,
)
from app.repositories.profiles import (
    ApprovedProfileRecord,
    ProfileNotFoundError,
    ProfileRepository,
    ProfileRepositoryError,
    ProfileValidationError,
)
from app.repositories.job_posts import (
    DEFAULT_LIST_LIMIT,
    MAX_LIST_LIMIT,
    NORMALIZED_KEY_VERSION,
    CreateReceivedResult,
    JobPostDuplicateError,
    JobPostNotFoundError,
    JobPostRecord,
    JobPostRepository,
    JobPostRepositoryError,
    JobPostStateError,
    JobPostValidationError,
    build_normalized_job_key,
    normalize_job_identity_component,
    sanitize_job_error_code,
    sanitize_job_error_message,
)
from app.repositories.tool_executions import (
    ToolExecutionNotFoundError,
    ToolExecutionRepository,
    ToolExecutionRepositoryError,
    ToolExecutionStateError,
    ToolExecutionValidationError,
    sanitize_arguments_summary,
    sanitize_error_code,
)

__all__ = [
    "AgentRunDuplicateError",
    "AgentRunNotFoundError",
    "AgentRunRepository",
    "AgentRunRepositoryError",
    "AgentRunStateError",
    "AgentRunValidationError",
    "ApprovedProfileRecord",
    "CreateReceivedResult",
    "DEFAULT_LIST_LIMIT",
    "ConversationDuplicateError",
    "ConversationMessageError",
    "ConversationNotFoundError",
    "ConversationPayloadError",
    "ConversationRepository",
    "ConversationRepositoryError",
    "JobPostDuplicateError",
    "JobPostNotFoundError",
    "JobPostRecord",
    "JobPostRepository",
    "JobPostRepositoryError",
    "JobPostStateError",
    "JobPostValidationError",
    "MAX_LIST_LIMIT",
    "NORMALIZED_KEY_VERSION",
    "PreferencesNotFoundError",
    "PreferencesRepository",
    "PreferencesRepositoryError",
    "PreferencesValidationError",
    "ProfileDraftNotFoundError",
    "ProfileDraftRecord",
    "ProfileDraftRepository",
    "ProfileDraftRepositoryError",
    "ProfileDraftStateError",
    "ProfileDraftValidationError",
    "ProfileNotFoundError",
    "ProfileRepository",
    "ProfileRepositoryError",
    "ProfileValidationError",
    "ToolExecutionNotFoundError",
    "ToolExecutionRepository",
    "ToolExecutionRepositoryError",
    "ToolExecutionStateError",
    "ToolExecutionValidationError",
    "build_normalized_job_key",
    "langgraph_thread_id",
    "normalize_job_identity_component",
    "sanitize_arguments_summary",
    "sanitize_error_code",
    "sanitize_job_error_code",
    "sanitize_job_error_message",
    "sanitize_run_error",
    "validate_structured_payload",
]
