export const CHAT_COPY = {
  newChat: 'New chat',
  openTailoredCv: 'Open tailored CV',
  sourceCitation: 'Source',
  activeCvSourceTitle: 'Source from CV',
  activeCvSourceSubtitle: 'Evidence used for this answer.',
  activeCvOpenOriginal: 'Open original CV',
  activeCvPartial: 'Some evidence is abbreviated or more pages remain unread.',
  close: 'Close',
  jobSave: 'Save job',
  cancel: 'Cancel',
  jobDetected: 'Job description detected',
  jobNotSaved: 'This job description has not been saved. Would you like to save it?',
  noMatch: 'No match result yet',
  saveAndEvaluate: 'Save job and evaluate',
  noSavedEvaluation: 'This job description does not have a saved evaluation yet.',
  evaluationUnavailable: 'The job may be saved, but evaluation is not available yet. Try again or send the message again.',
  evaluationError: 'The job could not be saved and evaluated. Try again or send the message again.',
  evaluationUnavailableTitle: 'Evaluation unavailable',
  connecting: 'Connecting…',
  runInterrupted: 'This activity was interrupted. Reload to see the latest state.',
  checkingSourceSupport: 'Checking source support',
  creatingTailoredCv: 'Creating a tailored CV',
  checkingJobMatches: 'Checking job matches',
  savingJob: 'Saving this job',
  checkingCvInformation: 'Checking CV information',
  checkingRequest: 'Checking your request',
  waiting: 'Waiting',
  complete: 'Complete',
  couldNotComplete: 'Could not complete',
  inProgress: 'In progress',
  stepCount: (count: number) => `${count} ${count === 1 ? 'step' : 'steps'}`,
  connectionLost: 'Connection lost. Your request may still be running.',
  waitingForConfirmation: (count: string) => `Waiting for your confirmation · ${count}`,
  completed: (count: string) => `Completed · ${count}`,
  unableToComplete: (count: string) => `Unable to complete · ${count}`,
  viewActivity: 'View activity',
  viewActivityCount: (count: string) => `View activity · ${count}`,
  hideActivity: 'Hide activity',
  runningStatus: (label: string) => `Running: ${label}`,
} as const;
